### ISSUE TITLE
st_make_valid moves to sf

### ISSUE THREAD

**Issue by edzer** [ipeaGIT/gtfs2gps#112]
Upcoming `lwgeom` no longer exports `st_make_valid`, but `sf` does. This will affect CRAN checks of gtfs2gps with
```
Error: object ‘st_make_valid’ is not exported by 'namespace:lwgeom'
Execution halted
ERROR: lazy loading failed for package ‘gtfs2gps’
```
Please fix and submit to CRAN.

**Comment by rafapereirabr** [comment]
Thank you for the heads up, @edzer .   @pedro-andrade-inpe , I checked our package code and it seems we are not using `st_make_valid` in any specific operation. So perhaps we can drop `@importFrom lwgeom st_make_valid` in the `zzz.R` script. Correct?

**Comment by pedro-andrade-inpe** [comment]
Thanks, @edzer.
@rafapereirabr, we do not use `st_make_valid`, but we need `lwgeom`, otherwise we get the following error in the tests:

```R
Converting shapes to sf objects
   Error in sf::st_length(geometry) : 
     package lwgeom required, please install it first
```

As we need `lwgeom`, we have to import at least one function from it to avoid check errors. I'll just replace `st_make_valid` by `st_geod_length`, which is the function called by `sf::st_length()`.

**Comment by rafapereirabr** [comment]
Thanks for the clarification. I guess we can close this issue then.
