### ISSUE TITLE
Use gtfsio::import_gtfs() inside read_gtfs() 

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#191]

**Comment by rafapereirabr** [comment]
I've implemented this in a new branch * gtfsio_test*. It seems to be working fine, but we should discuss a few details in our next meeting.

**Comment by pedro-andrade-inpe** [comment]
@rafapereirabr I tested this branch and the only observation I have is that there is a warning in the tests:
```
Some columns are type 'integer64' but package bit64 is not installed. Those columns will print as strange looking 
floating point data. There is no need to reload the data. Simply install.packages('bit64') to obtain the integer64 
print method and print the data again.
```

Should we add `bit64` as a dependency of `gtfs2gps`?

**Comment by rafapereirabr** [comment]
Hmm. This is strange, because the `gtfsio` package does not use nor depend on `bit64`

**Comment by dhersz** [comment]
Hey guys, I just randomly stumbled across this issue. `{gtfsio}` doesn't import `bit64`, but `{data.table}` suggests it, so I guess that's where the issue comes from.

Since `bit64` was listed in `gtfs2gps` `Imports` you'll probably receive a complain from CRAN because you are not using it explicitly (i.e. through a function call). To prevent yourselves from this possible future complain I would:

- Move `bit64` from `Imports` to `Suggests`;
- Wrap any `bit64` reliant test/example in a `requireNamespace()` call.

An example:

```r
if (requireNamespace("bit64", quietly = TRUE)) {
  run_test_that_requires_bit64()
}
```

This way CRAN doesn't complain about importing the package, `bit64` still gets installed when `gtfs2gps` is installed and if someone install `gtfs2gps` without installing its "soft" dependencies he/she won't face an error when trying to check/test the package. 

Hope this helps, cheers!
