### ISSUE TITLE
should gtfs2gps includes as gtfs class, such as gtfstools?

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2gps#238]
Since we are migrating some functions to `gtfstools`, we might have some issues to use `gtfs2gps` and `gtfstools` interchangeably. 
```r
> raw_gtfs <- gtfs2gps::read_gtfs("article/gtfs_sptrans.zip")
> tmp_gtfs <- raw_gtfs %>% 
+   gtfs2gps::filter_by_shape_id("63442") %>% 
+   gtfstools::filter_by_trip_id("1012-10-0_2")
Error in gtfstools::filter_by_trip_id(., "1012-10-0_2") : 
  Assertion on 'gtfs' failed: Must inherit from class 'dt_gtfs', but has classes 'gtfs','list'.
```
Should be add a gtfs class into our package?

**Comment by rafapereirabr** [comment]
If if are going to depend more heavily on `gtfstools`, it looks like our functions will have use the `gtfs` class created by @dhersz .

**Comment by pedro-andrade-inpe** [comment]
Fully agree!

**Comment by pedro-andrade-inpe** [comment]
I think this is a question  involving gtfstools and gtfsio. Both have a read function that are not compatible. Using only gtfstools it works:

```R
sp <-  gtfstools::read_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps"), quiet = TRUE)

sp %>% 
  gtfstools::filter_by_shape_id("52421") %>% 
  gtfstools::filter_by_trip_id("121G-10-0")
```

However, rading with gtfsio but using the functions from gtfstools it stops with an error:

```R
sp <-  gtfsio::import_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps"), quiet = TRUE)

sp %>% 
  gtfstools::filter_by_shape_id("52421") %>% 
  gtfstools::filter_by_trip_id("121G-10-0")
```

```
Error in gtfstools::filter_by_shape_id(., "52421") : 
  Assertion on 'gtfs' failed: Must inherit from class 'dt_gtfs', but has classes 'gtfs','list'.
```

**Comment by pedro-andrade-inpe** [comment]
We use `gtfsio::import_gtfs()` to read the data, that's why the error occurs. Should we use `gtfstools::read_gtfs()` instead?

**Comment by rafapereirabr** [comment]
> ```r
> gtfstools
> ```

This could be an issue for `gtfstools` perhaps? @dhersz

**Comment by rafapereirabr** [comment]
> I think this is a question involving gtfstools and gtfsio. Both have a read function that are not compatible. Using only gtfstools it works:
> 
> ```r
> sp <-  gtfstools::read_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps"), quiet = TRUE)
> 
> sp %>% 
>   gtfstools::filter_by_shape_id("52421") %>% 
>   gtfstools::filter_by_trip_id("121G-10-0")
> ```
> 
> However, rading with gtfsio but using the functions from gtfstools it stops with an error:
> 
> ```r
> sp <-  gtfsio::import_gtfs(system.file("extdata/saopaulo.zip", package = "gtfs2gps"), quiet = TRUE)
> 
> sp %>% 
>   gtfstools::filter_by_shape_id("52421") %>% 
>   gtfstools::filter_by_trip_id("121G-10-0")
> ```
> 
> ```
> Error in gtfstools::filter_by_shape_id(., "52421") : 
>   Assertion on 'gtfs' failed: Must inherit from class 'dt_gtfs', but has classes 'gtfs','list'.
> ```

This could be an issue for gtfstools perhaps? @dhersz

**Comment by rafapereirabr** [comment]
> We use `gtfsio::import_gtfs()` to read the data, that's why the error occurs. Should we use `gtfstools::read_gtfs()` instead?

Yes, I think we should we probably use `gtfstools::read_gtfs()` directly

**Comment by dhersz** [comment]
@mpadge has brought my attention to this matter in a issue he opened in gtfstools as well.

Initially, `gtfsio::import_gtfs()` was created to develop a "standard compliant" GTFS-reading function that was fast and wasn't opinionated, in the sense that data is read as much as possible "as is" (e.g. dates, which in the specification are defined as YYYYMMDD are not read as `Date`, but as an `integer`).

`gtfstools::read_gtfs()`, as well as `tidytransit::read_gtfs()`, on the other, is opinionated. For example, I much prefer working with `Date`s than with `integer` representing dates. The `tidytransit` folks prefer using tibbles over data.tables, etc.

Mark suggested ditching `gtfstools::read_gtfs()` in favour of converting from standards in the beginning of every `gtfstools` function (which wouldn't slow the proccess down if we used memoisation), but I fear I (and the users of gtfstools, tidytransit and any other opinionated packages) would lose the "convenience" of manipulating the GTFS without the package functions. What if I wanted to add a few days to all dates in my GTFS? Then I'd have to manually convert the dates from integers to Dates, proceed with the operation and convert it back to integer, so it's standard compliant and I can use it with the functions that rely on it being standard compliant. What if I'm a tidytransit user that am used to the `tidyverse` syntax, in opposition to `data.table`'s, and want to left join the stops table to the stop_times table? Then I'd have to convert it to tibble (`gtfsio` reads tables as data.tables), proceed with the operation, and convert them back to data.table afterwards.

The `dt_gtfs` then was a way to distinguish between these different opinionated representations. While all GTFS representations inherit from gtfs and list, only the ones created by gtfstools inherit from dt_gtfs. Then gtfstools' functions can make sure that they're dealing with an object that is compatible with the syntax used in the function body (e.g. I'm not trying to use data.table syntax to edit a tidytransit GTFS object).

Sorry if I extending myself too much here, but my key point here is that `gtfstools` (and `tidytransit`, `gtfs2gps`, etc) has an opinionated view on how GTFS files should be interpreted in R, whereas I initially imagined `gtfsio` as more "agnostic" in this sense.

However, I don't want to finish the debate here. Unfortunately I've been busy with other projects since Mark first opened the issue in gtfstools repo and haven't had the time to put much thought into it yet, but interoperability between packages is still a huge preoccupation of mine and I'd like to hear your thoughts on how we should solve this issue.

I thought, for example, that `convert_to_standard` and `convert_from_standard` could be generic functions created in `gtfsio`, and the opinionated packages would implement their methods for these generics. Then if I'm trying to pass a tidygtfs to a `gtfstools` function I could test if it's inherits from `dt_gtfs`, and if not, but it does inherit from `gtfs`, I'd just need to use `convert_to_standard(gtfs)` and then `convert_from_standard(gtfs)`. It seems that it could work, but not sure if it's the best approach.

**Comment by mpadge** [comment]
Really appreciate the thoughts here, and agree with @dhersz that this really is important to "get right", whatever that might end up meaning. My suggestion would be to retain ˋgtfsioˋ as the single go-to location for reading feeds, but to extend that package along the lines of [ˋtxboxˋ for time series](https://github.com/christophsax/tsbox). That package uses a ˋts_<target format>ˋ notation that we need not necessarily adopt here, but having some kind of convert function(s) in ˋgtfioˋ would centralise and standardise formats for everybody. But open to other ideas too, and mostly looking forward to seeing where this discussion goes.

**Comment by rafapereirabr** [comment]
This discussion is indeed much needed and your thoughts much appreciated. Two quick comments here:

**An specific comment regarding `gtfs2gps`:**

- We are vey much interested in making `gtfs2gps` fully compatible with (dependent on) `gtfstools`. Hence why we started migrating many GTFS manipulation functions from `gtfs2gps` to `gtfstools`, and we now import them from `gtfstools`. This will require some work on the `gtfs2gps` side of things (particularly for dealing with departure and arrival times) but we will eventually get there.

**A more broad comment regarding interoperability between packages:**
- I think we all agree `gtfsio` should indeed be agnostic and it does a terrific work job at it.
- I like having a `gtfs2gps::read_gtfs()` that builds on top of `gtfsio::import_gtfs()` or `gtfstools::read_gtfs()` by adding some additional checks that cater to our specific needs (e.g. `gtfs2gps` does not work if a GTFS feed doesn't have a `shapes.txt` file).
- There is a high chance that some people will be going back and forth trying to use functions from `gtfstools` and `tidytransity` on the same object (I've seen it a couple times already). Some people might also get a bit confused since `read_gtfs()` has now become a common function name shared across packages. So yes, interoperability is a key concern.
- I like @mpadge's suggestion of having a set of convert functions in ˋgtfioˋ, making it something like a universal plug that we can use in our packages. I don't think we can (or want to) achieve absolute seamless interoperability between packages but these convert functions could be a major step in that direction.
