### ISSUE TITLE
writing a merged gtfs list got: 'gtfs' must inherit from the 'gtfs' class

### ISSUE THREAD

**Issue by TheYuanLiao** [ipeaGIT/gtfs2gps#242]
Please the below code block.
``` r
library(gtfs2gps)
library(dplyr)

se_sj <- "dbs/gtfs/sweden_regional_sj.zip"
se_sl <- "dbs/gtfs/sweden_regional_sl.zip"
se_vt <- "dbs/gtfs/sweden_regional_vt.zip"
se_skane <- "dbs/gtfs/sweden_regional_skane.zip"

gtfs_list <- list(se_sj, se_sl, se_vt, se_skane)

new_gtfs <- merge_gtfs_feeds(gtfs_list)

zipfile <- "dbs/otp/vgr_v2/gtfs_vgr_v2.zip"
write_gtfs(new_gtfs, zipfile)
```

And `write_gtfs(new_gtfs, zipfile)` gives me:
Error: 'gtfs' must inherit from the 'gtfs' class.

This will not be an issue if only read_gtfs and then write_gtfs. Does `new_gtfs` have the right class? Please help. Thanks!

**Comment by rafapereirabr** [comment]
Hi @TheYuanLiao ! Thanks for opening this issue. This is a bug in the `gtfs2gps::merge_gtfs_feeds` function. The output of this function should have a classe `"gtfs" "list"`.

Having said that, we need to clarify that most if not all data manipulation functions in the `gtfs2gps` package (including the `merge_gtfs_feeds` function) are gradually being migrated to the [`gtfstools` package](https://github.com/ipeaGIT/gtfstools). The operation you're trying to do can be done with this code. As you see, very similar function names and syntax so that `gtfs2gps` and `gtfstools` can be used together seamlessly.

```
library(gtfstools)

# gtfs files
gtfs1 <- system.file("extdata/poa_gtfs.zip", package = "gtfstools")
gtfs2 <- system.file("extdata/spo_gtfs.zip", package = "gtfstools")

# read gtfs data
gtfs1 <- gtfstools::read_gtfs(gtfs1)
gtfs2 <- gtfstools::read_gtfs(gtfs2)

# merge gtfs feeds
gtfs_list <- list(gtfs1, gtfs2)
gtfs_new <- gtfstools::merge_gtfs(list(gtfs1, gtfs1))

# save
gtfstools::write_gtfs(gtfs_new, path = 'gtfs_new.zip')

```

**Comment by TheYuanLiao** [comment]
Hi Rafa, thank you very much for the quick response. This solved the error.
