### ISSUE TITLE
Distance between interpolated points

### ISSUE THREAD

**Issue by Joaobazzo** [ipeaGIT/gtfs2gps#27]
Although our script sets the spatial resolution of `15` m, our interpolated stop times file are displaying different values for `dist`
```
> new_stoptimes
       shape_id  id route_type shape_pt_lon shape_pt_lat stop_id stop_sequence      dist
  1: shape804-I   1          3    -38.47761    -3.726532    2649             1 11.218464
  2: shape804-I   2          3    -38.47767    -3.726615      NA            NA 11.218464
  3: shape804-I   3          3    -38.47773    -3.726697      NA            NA 13.953559
  4: shape804-I   4          3    -38.47762    -3.726766      NA            NA 13.953559
  5: shape804-I   5          3    -38.47752    -3.726835      NA            NA 13.953559
 ---                                                                                    
363: shape804-I 363          3    -38.48439    -3.738244      NA            NA 13.422701
364: shape804-I 364          3    -38.48444    -3.738353      NA            NA 13.422701
365: shape804-I 365          3    -38.48450    -3.738462      NA            NA  7.889898
366: shape804-I 366          3    -38.48453    -3.738523      NA            NA  7.889898
367: shape804-I 367          3    -38.48457    -3.738583    6079            13       NaN
```

I've tried changing the coordinate system to UTM before estimating the distances, but the results were the same. Also, the function `st_distance()` between consecutive points behaves similarly.  I think it has something to do with the `st_cast` function, but so far couldn't figure out.

**Comment by pedro-andrade-inpe** [comment]
The algorithm used internally by comes from PostGIS:

http://postgis.net/docs/doxygen/2.3/da/de7/liblwgeom_8h_a24f17b71347cf63fca76aec7917cd34e.html

Because of that, the value of `15m` is in fact the maximum distance between points. That's why we have the values for dist as shown above.

What is really strange is that in some tests it produces values for `dist` greater than `15m`. It seems to be a bug, but I'm still investigating.
