### ISSUE TITLE
Probably a bug in filter_day_period

### ISSUE THREAD

**Issue by rafapereirabr** [ipeaGIT/gtfs2gps#96]
In theory, the result should be identical whether (1) we filter a day period of a gtfs dataset before converting it to gps-like data.table, or (2) we convert a gtfs to gps-like data.table and then filter a day period. I've tried a test below and the results are very different. This should gives us an idea of where and why the `filter_day_period` is nor working properly.

```
library(gtfs2gps)
library(data.table)


# read local GTFS.zip
gtfs_zip <- system.file("extdata/fortaleza.zip", package="gtfs2gps" )
gtfs_dt <- gtfs2gps::read_gtfs(gtfs_zip)


### 1) Filter before gtfs2gps
  
  # subset time interval
  gtfs_filtered <- gtfs2gps::filter_day_period(gtfs_dt, period_start = "07:00:", period_end = "07:59")
  
  # Convert GTFS data into a data.table with GPS-like records
  gps_before <- gtfs2gps::gtfs2gps(gtfs_filtered, spatial_resolution = 15, progress = T, parallel = T )

  
### 2) Filter after gtfs2gps
  
  # Convert GTFS data into a data.table with GPS-like records
  gps <- gtfs2gps::gtfs2gps(gtfs_dt, spatial_resolution = 15, progress = T, parallel = T )

  # subset time interval
  gps_after <- gps[ between(departure_time, as.ITime("07:00:"), as.ITime("07:59"))]
  
  
  nrow(gps_before)
  nrow(gps_after)

```

**Comment by pedro-andrade-inpe** [comment]
Suppose that we are creating GPS points with interval of one minute (using time instead of space to simplify, but that would not change the reasoning). Suppose also a trip with the following stops: 6h55, 7h10, 7h25, 7h40, 7h55, 8h10. If we filter before, we will have the following stops: 7h10, 7h25, 7h40, 7h55. With these stops, we would create 46 GPS points (7h10, 7h11, 7h12, ..., 7h55). If we filter after, we will have a GPS with the following points: 6h55, 6h56, ..., 8h10. Filtering by time we will have 60 points (7h00, 7h01, ..., 7h59). Therefore we will have 14 more points when we filter after. This situation occurs in all trips that start before 7h00 and/or end after 7h59. That's why there are more points whe we filter after.

A strange output is that when we filter after it is producing 88% more points. It seems to me that the difference should be much less, like 10-20%. I will investigate that.

**Comment by rafapereirabr** [comment]
This issue might probably emerge when there are `NA` values in the original  `departure_time` column of the `stop_times.txt` file. If this is the case, we should probably create a condition that the `filter_day_period` function can only be applied to a GTFS.zip file when there are no missing values in the original  `departure_time` column. 

If this column has a missing value, then the function simply returns an ERROR message suggesting that the user filters the day period in the 'gps-like' data,table

**Comment by pedro-andrade-inpe** [comment]
With the changes in the last months to fix some issues the difference has dropped from 88% to 27%, which is much more reasonable. @rafapereirabr should we close this issue?

**Comment by rafapereirabr** [comment]
It sounds good to me.
